### ISSUE TITLE
It is possible to collaborate in the project?

### ISSUE THREAD

**Issue by jabrena** [jmccormack200/RPLidar#2]
Hi,

I am testing this project on Lego Mindstorms Platform with some boards and I would like to integrate this Driver with a Java Development so maybe I will have to create a new script. Do you like if I do some pull requests?

Juan Antonio

**Comment by jmccormack200** [comment]
Hey Juan, 

Sorry for the super late reply. Feel free to submit pull requests or fork and edit on your own. I no longer have access to an RP Lidar (Graduated) so I can't test your code but I'm always happy to help out and answer questions you may have.
